"""initial current schema

Revision ID: 2e6d88e66490
Revises: 
Create Date: 2026-06-18 13:23:44.090974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6d88e66490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('kiosk_pin', sa.String(length=10), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('cpr_has_license', sa.Boolean(), nullable=True),
    sa.Column('cpr_license_name', sa.String(length=150), nullable=True),
    sa.Column('cpr_expiration_date', sa.String(length=20), nullable=True),
    sa.Column('evoc_has_license', sa.Boolean(), nullable=True),
    sa.Column('evoc_license_name', sa.String(length=150), nullable=True),
    sa.Column('evoc_expiration_date', sa.String(length=20), nullable=True),
    sa.Column('emt_has_license', sa.Boolean(), nullable=True),
    sa.Column('emt_license_name', sa.String(length=150), nullable=True),
    sa.Column('emt_expiration_date', sa.String(length=20), nullable=True),
    sa.Column('paramedic_has_license', sa.Boolean(), nullable=True),
    sa.Column('paramedic_license_name', sa.String(length=150), nullable=True),
    sa.Column('paramedic_expiration_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('insurance', sa.String(length=150), nullable=True),
    sa.Column('member_id', sa.String(length=100), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('copay_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_notes', sa.Text(), nullable=True),
    sa.Column('default_service_level', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('oxygen_required', sa.Boolean(), nullable=True),
    sa.Column('stairs', sa.Boolean(), nullable=True),
    sa.Column('special_equipment_notes', sa.Text(), nullable=True),
    sa.Column('facility_name', sa.String(length=150), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('dispatcher_name', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_of_call', sa.String(length=20), nullable=True),
    sa.Column('trip_date', sa.String(length=20), nullable=True),
    sa.Column('pickup_time', sa.String(length=20), nullable=True),
    sa.Column('appointment_time', sa.String(length=20), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('dropoff_address', sa.Text(), nullable=True),
    sa.Column('caller_type', sa.String(length=100), nullable=True),
    sa.Column('call_type', sa.String(length=100), nullable=True),
    sa.Column('service_level', sa.String(length=100), nullable=True),
    sa.Column('caller_phone', sa.String(length=30), nullable=True),
    sa.Column('caller_note', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('missing_critical_fields', sa.Text(), nullable=True),
    sa.Column('missing_optional_fields', sa.Text(), nullable=True),
    sa.Column('missing_info_explanation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(length=150), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('medical_id', sa.Integer(), nullable=True),
    sa.Column('assist1_id', sa.Integer(), nullable=True),
    sa.Column('assist2_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assist1_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['assist2_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['medical_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_crew_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.String(length=20), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('truck_number', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('shift_type', sa.String(length=10), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('medical_id', sa.Integer(), nullable=True),
    sa.Column('assist1_id', sa.Integer(), nullable=True),
    sa.Column('assist2_id', sa.Integer(), nullable=True),
    sa.Column('first_patient', sa.String(length=255), nullable=False),
    sa.Column('next_patients', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dispatch_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assist1_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['assist2_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['medical_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_pay_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pay_type', sa.String(length=20), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('overtime_rate', sa.Float(), nullable=True),
    sa.Column('overtime_after', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('call_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.String(length=50), nullable=True),
    sa.Column('assigned_by', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['daily_crew_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_body', sa.String(length=200), nullable=True),
    sa.Column('issued_date', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('exported_at', sa.String(length=50), nullable=True),
    sa.Column('exported_to', sa.String(length=50), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.String(length=50), nullable=False),
    sa.Column('clock_out', sa.String(length=50), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['notification_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_prefs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prefs_json', sa.Text(), nullable=True),
    sa.Column('push_sub_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification_prefs')
    op.drop_table('user_notification')
    op.drop_table('time_entry')
    op.drop_table('pay_period')
    op.drop_table('employee_document')
    op.drop_table('call_assignment')
    op.drop_table('user')
    op.drop_table('employee_pay_config')
    op.drop_table('daily_crew_unit')
    op.drop_table('crew_preset')
    op.drop_table('call')
    op.drop_table('patient')
    op.drop_table('notification_event')
    op.drop_table('employee')
    op.drop_table('organization')
    # ### end Alembic commands ###
