"""add push_sub_json to user_notification_prefs

Revision ID: 4ad0f24009a3
Revises: 9a96819d9969
Create Date: 2026-06-17 11:59:20.169233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad0f24009a3'
down_revision = '9a96819d9969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification_prefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_sub_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification_prefs', schema=None) as batch_op:
        batch_op.drop_column('push_sub_json')

    # ### end Alembic commands ###
