"""Calendar sources + Task participants / assign-to-all

Revision ID: e5a9c7d1b2f3
Revises: d4f8a1c2e3b9
Create Date: 2026-07-14

Hand-written (not autogenerated) so it introduces only the new objects for the
expanded Calendar event sources and the Task participants / assign-to-all
feature, without disturbing the pre-existing model/migration index drift
(undeclared performance indexes must be preserved).

Adds:
  * employee.dob                      — employee birthday events
  * vehicle.{inspection,registration,insurance}_expiry, next_maintenance_date
                                        — vehicle compliance/maintenance events
  * task.visible_to_all               — "assign to everyone" announcements
  * task_participant(task_id, employee_id) — additional task viewers
"""

from alembic import op
import sqlalchemy as sa

revision = "e5a9c7d1b2f3"
down_revision = "d4f8a1c2e3b9"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("employee", sa.Column("dob", sa.String(length=20), nullable=True))

    op.add_column("vehicle", sa.Column("inspection_expiry", sa.String(length=20), nullable=True))
    op.add_column("vehicle", sa.Column("registration_expiry", sa.String(length=20), nullable=True))
    op.add_column("vehicle", sa.Column("insurance_expiry", sa.String(length=20), nullable=True))
    op.add_column("vehicle", sa.Column("next_maintenance_date", sa.String(length=20), nullable=True))

    # server_default so existing rows backfill to false; the ORM default handles new rows.
    op.add_column("task", sa.Column("visible_to_all", sa.Boolean(), nullable=False, server_default=sa.false()))

    op.create_table(
        "task_participant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "employee_id", name="uq_task_participant"),
    )


def downgrade():
    op.drop_table("task_participant")
    # batch_alter_table so column drops work on any SQLite version.
    with op.batch_alter_table("task") as batch:
        batch.drop_column("visible_to_all")
    with op.batch_alter_table("vehicle") as batch:
        batch.drop_column("next_maintenance_date")
        batch.drop_column("insurance_expiry")
        batch.drop_column("registration_expiry")
        batch.drop_column("inspection_expiry")
    with op.batch_alter_table("employee") as batch:
        batch.drop_column("dob")
