"""Fleet Management foundation

Revision ID: f1b2c3d4e5a6
Revises: e5a9c7d1b2f3
Create Date: 2026-07-15

Hand-written (not autogenerated) so it introduces only the new Fleet objects and
does not disturb the pre-existing model/migration index drift — autogenerate
would try to drop the performance indexes that live in migrations but are not
declared on the models.

Adds:
  * Vehicle: capabilities + identity (VIN/plate/year/make/model/colour/ownership),
    operational status, retire fields, odometer cache, maintenance summary
  * vehicle_odometer_entry  — mileage history (the odometer is never one
    mutable number)
  * vehicle_maintenance_record — scheduled/completed work
  * daily_crew_unit.vehicle_id — the physical vehicle a shift runs, NULLABLE:
    legacy shifts stored a free-text truck_number that frequently matches no
    fleet record, and history must not be rewritten to satisfy a new FK.
    truck_number is kept as the display/snapshot value.
"""

from alembic import op
import sqlalchemy as sa

revision = "f1b2c3d4e5a6"
down_revision = "e5a9c7d1b2f3"
branch_labels = None
depends_on = None


VEHICLE_COLUMNS = [
    ("capabilities", sa.Text()),
    ("vin", sa.String(length=32)),
    ("license_plate", sa.String(length=20)),
    ("plate_state", sa.String(length=10)),
    ("model_year", sa.Integer()),
    ("make", sa.String(length=50)),
    ("model", sa.String(length=50)),
    ("color", sa.String(length=30)),
    ("ownership_type", sa.String(length=20)),
    ("out_of_service_reason", sa.Text()),
    ("retired_at", sa.String(length=50)),
    ("retired_reason", sa.Text()),
    ("current_odometer", sa.Integer()),
    ("odometer_unit", sa.String(length=5)),
    ("last_odometer_update", sa.String(length=50)),
    ("last_service_date", sa.String(length=20)),
    ("last_service_mileage", sa.Integer()),
    ("next_service_mileage", sa.Integer()),
    ("maintenance_notes", sa.Text()),
]


def upgrade():
    for name, type_ in VEHICLE_COLUMNS:
        op.add_column("vehicle", sa.Column(name, type_, nullable=True))

    # Non-null columns need a server_default so existing rows backfill.
    op.add_column("vehicle", sa.Column(
        "operational_status", sa.String(length=30), nullable=True, server_default="in_service"))
    op.add_column("vehicle", sa.Column(
        "is_retired", sa.Boolean(), nullable=False, server_default=sa.false()))

    # Plain ADD COLUMN, deliberately WITHOUT a database-level FK constraint.
    #
    # Adding one to an existing SQLite table needs a full batch table rebuild,
    # and on this database that rebuild is unsafe: the schema carries known drift
    # (indexes that exist in migrations but are not declared on the models), so a
    # rebuild silently drops them — a first attempt at this migration did exactly
    # that and left an orphaned _alembic_tmp_daily_crew_unit behind.
    #
    # The FK is declared on the model, which is what SQLAlchemy uses for the
    # relationship and joins. That matches every other FK in this schema (org_id,
    # cancelled_by, ...), which are likewise model-only. Reconciling FKs at the
    # database level belongs to the migration-reconciliation block, not here.
    op.add_column("daily_crew_unit", sa.Column("vehicle_id", sa.Integer(), nullable=True))

    op.create_table(
        "vehicle_odometer_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("reading", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=5), nullable=True),
        sa.Column("recorded_at", sa.String(length=50), nullable=False),
        sa.Column("recorded_by", sa.Integer(), nullable=True),
        sa.Column("recorded_by_name", sa.String(length=150), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"]),
        sa.ForeignKeyConstraint(["recorded_by"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # Odometer history is always read per vehicle, newest first.
    op.create_index("ix_vehicle_odometer_entry_vehicle_id", "vehicle_odometer_entry", ["vehicle_id"])

    op.create_table(
        "vehicle_maintenance_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="scheduled"),
        sa.Column("scheduled_date", sa.String(length=20), nullable=True),
        sa.Column("completed_date", sa.String(length=20), nullable=True),
        sa.Column("odometer_at_service", sa.Integer(), nullable=True),
        sa.Column("vendor", sa.String(length=150), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=50), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vehicle_maintenance_record_vehicle_id", "vehicle_maintenance_record", ["vehicle_id"])
    # The Calendar queries scheduled maintenance by date range.
    op.create_index("ix_vehicle_maintenance_record_scheduled_date", "vehicle_maintenance_record", ["scheduled_date"])


def downgrade():
    op.drop_index("ix_vehicle_maintenance_record_scheduled_date", table_name="vehicle_maintenance_record")
    op.drop_index("ix_vehicle_maintenance_record_vehicle_id", table_name="vehicle_maintenance_record")
    op.drop_table("vehicle_maintenance_record")

    op.drop_index("ix_vehicle_odometer_entry_vehicle_id", table_name="vehicle_odometer_entry")
    op.drop_table("vehicle_odometer_entry")

    # Plain DROP COLUMN (SQLite 3.35+) — no batch rebuild, for the same reason
    # the upgrade avoids one: a rebuild would drop the schema's undeclared
    # performance indexes.
    op.drop_column("daily_crew_unit", "vehicle_id")

    op.drop_column("vehicle", "is_retired")
    op.drop_column("vehicle", "operational_status")
    for name, _type in reversed(VEHICLE_COLUMNS):
        op.drop_column("vehicle", name)
